=== BekkariYa/DOCMEN/ex05_01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="messages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="message" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dest" type="xs:string"/>
              <xs:element name="dest" type="xs:string" minOccurs="0"/>
              <xs:element name="contenu" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="numero" type="xs:int" use="required"/>
            <xs:attribute name="date" type="xs:date"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== BekkariYa/DOCMEN/ex5_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ex05_01.xsd">
<message numero="1" date="2021-01-01">
<dest>promo2021</dest>
<dest >Pierre Nerzic</dest>
<contenu>Bonne année !</contenu>
</message>
<message numero="2">
<dest>promo2021</dest>
<contenu>Bonne rentrée !</contenu>
</message>

</messages>
