=== BekkariYa/DOCMEN/ex07.dtd
<!ELEMENT courses (coure+)>
<!ELEMENT coure (gagnant,second,les_arbitres,debut,fin)>
<!ATTLIST coure numÃ©ro CDATA #IMPLIED>
<!ELEMENT gagnant (#PCDATA)>
<!ATTLIST gagnant temps CDATA #REQUIRED>
<!ELEMENT second (#PCDATA)>
<!ELEMENT les_arbitres (arbitre1,arbitre2)>
<!ELEMENT arbitre1 (#PCDATA)>
<!ATTLIST arbitre1 nom CDATA #IMPLIED>
<!ELEMENT arbitre2 (#PCDATA)>
<!ATTLIST arbitre2 nom CDATA #IMPLIED>
<!ELEMENT debut (#PCDATA)>
<!ATTLIST debut format_heure CDATA #IMPLIED>
<!ELEMENT fin (#PCDATA)>

=== BekkariYa/DOCMEN/exo7.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE courses SYSTEM "ex07.dtd" >



<courses>
    <coure numéro="c8">
        <gagnant temps="35">Dupont</gagnant>
        <second>durand</second>
        <les_arbitres>
            <arbitre1 nom="TMartinT"/>
            <arbitre2 nom="TLegrandT"/>
        </les_arbitres>
        <debut format_heure="hh:mm">13:00</debut>
        <fin>13:53</fin>
    </coure>

    <coure numéro="c9">
        <gagnant temps="35">Dupont</gagnant>
        <second>durand</second>
        <les_arbitres>
            <arbitre1 nom="TMartinT"/>
            <arbitre2 nom="TLegrandT"/>
        </les_arbitres>
        <debut format_heure="hh:mm">13:00</debut>
        <fin>13:53</fin>
    </coure>
</courses>
