=== BekkariYa/DOCMEN/ex4_02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="inscripition" >

    <xs:complexType >
        <xs:sequence>

            <xs:element name="ue" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titre" type="xs:string" />
                        <xs:element name="resume" type="xs:string" />
                        <xs:element name="inscrit" minOccurs="1">
                             <xs:complexType>
                                <xs:attribute name="num"  use="required"></xs:attribute>
                          </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="code" use="required"></xs:attribute>
                </xs:complexType>

            </xs:element>
                

            <xs:element name="etudiant" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string" />
                        <xs:element name="adresse" type="xs:string" />
                    </xs:sequence>
                    <xs:attribute name="id" use="required"></xs:attribute>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>

  </xs:element>

</xs:schema>

=== BekkariYa/DOCMEN/ex4_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<inscripition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ex4_02.xsd">
    <ue code="UE_CODE_1">
        <titre>Titre de l'UE 1</titre>
        <resume>Résumé de l'UE 1</resume>
        <inscrit num="ID_ETUDIANT_1" />
    </ue>
    <etudiant id="ID_ETUDIANT_1">
        <nom>Nom de l'étudiant 1</nom>
        <adresse>Adresse de l'étudiant 1</adresse>
    </etudiant>
</inscripition>
