=== BekkariYa/DOCMEN/exo6.dtd
<!ELEMENT cv (etatcivil, formation+, experience*)>
<!ELEMENT etatcivil (nom, prenom, age, lien)>
<!ELEMENT formation (titre, data, mention?, description?)>
<!ELEMENT experience (libelle, fonction, annee, observation?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT lien (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT libelle (#PCDATA)>
<!ELEMENT mention (#PCDATA)>
<!ELEMENT fonction (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT observation (#PCDATA)>

=== BekkariYa/DOCMEN/ex6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "exo6.dtd">
<cv>
    <etatcivil>
        <nom></nom>
        <prenom></prenom>
        <age></age>
        <lien></lien>
    </etatcivil>
    <formation>
        <titre></titre>
        <data></data>
        <mention></mention>
        <description></description>
    </formation>
</cv>
